apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: maikonb/udagram-api-feed
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"          
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v0/feed
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3            
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: POSTGRES_USERNAME        
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: POSTGRES_PASSWORD 
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: POSTGRES_HOST 
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: POSTGRES_DB 
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: AWS_BUCKET 
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: AWS_REGION                                 
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: AWS_PROFILE                                 
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: udagram-env-vars
                key: JWT_SECRET                                 
                                                             